version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"  
    volumes:
      - ./postgres/data:/var/lib/postgresql/data  
      - ./postgres/init:/docker-entrypoint-initdb.d
    restart: always

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SESSION_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${SESSION_DB_PASSWORD}
    ports:
      - "${SESSION_DB_PORT}:27017"
    volumes:
      - ./mongo/data:/data/db