--Populate catalog table console dictionary
INSERT INTO console_dictionary (name, type) VALUES
('generic', 'generic'),
('playstation', 'desktop'),
('playstation 2', 'desktop'),
('playstation 3', 'desktop'),
('playstation 4', 'desktop'),
('playstation 5', 'desktop'),
('psp', 'portable'),
('psp go', 'portable'),
('ps vita', 'portable'),
('xbox', 'desktop'),
('xbox 360', 'desktop'),
('xbox one', 'desktop'),
('xbox series x', 'desktop'),
('xbox series s', 'desktop'),
('nintendo entertainment system', 'desktop'),
('super nintendo', 'desktop'),
('virtual boy', 'desktop'),
('nintendo 64', 'desktop'),
('gamecube', 'desktop'),
('wii', 'desktop'),
('wii u', 'desktop'),
('nintendo switch', 'desktop'),
('nintendo switch lite', 'portable'),
('game boy', 'portable'),
('game boy color', 'portable'),
('game boy advance', 'portable'),
('game boy advance sp', 'portable'),
('nintendo ds', 'portable'),
('nintendo 3ds', 'portable'),
('new nintendo 3ds', 'portable'),
('game & watch', 'portable'),
('sega master system', 'desktop'),
('sega genesis', 'desktop'),
('sega saturn', 'desktop'),
('sega dreamcast', 'desktop'),
('sega cd', 'desktop'),
('game gear', 'portable'),
('genesis nomad', 'portable'),
('pc', 'desktop');

--Populate catalog table gender
INSERT INTO gender (name) VALUES
('action'),
('adventure'),
('rpg'),
('fps'),
('sports'),
('simulation'),
('strategy'),
('horror'),
('mmorpg'),
('fighting'),
('puzzle'),
('racing'),
('sandbox'),
('music/rhythm'),
('platformer'),
('survival'),
('stealth');

--Populate catalog table user_role
INSERT INTO user_role (role) VALUES
('admin'),
('client');